[tools]
# For Mise
usage = "latest"
# CLI Tools
ripgrep = "latest"
fzf = "latest"
eza = "latest"
starship = "latest"
zoxide = "latest"
neovim = "latest"
gemini-cli = "latest"
# Languages/Language tools
go = "latest"
lua = "5.1"
node = "lts"
tree-sitter = "latest"
uv = "latest"

[settings]
experimental = true
