[tools]
# For Mise
usage = "latest"
# CLI Tools
ripgrep = "latest"
fzf = "latest"
eza = "latest"
starship = "latest"
zoxide = "latest"
neovim = "latest"
gemini-cli = "latest"
# Languages/Language tools
node = "lts"
uv = "latest"
go = "latest"
tree-sitter = "latest"
