[tools]
# For Mise
usage = "latest"
# CLI Tools
eza = "latest"
fastfetch = "latest"
fzf = "latest"
gemini-cli = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"
# Languages/Language tools
node = "lts"
task = "latest"
tree-sitter = "latest"
uv = "latest"

[settings]
experimental = true
